[package]
name = "vedtoob"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
bat = "0.26.1"
clap = { version = "4.5.53", features = ["derive"] }
reqwest = { version = "0.12.25", features = ["blocking", "json"] }
serde_json = "1.0.145"
